# Generated by Django 3.1.5 on 2021-09-16 00:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Informatique', max_length=200, verbose_name='Name')),
            ],
            options={
                'verbose_name_plural': 'Departement',
            },
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('phone_number', models.CharField(max_length=21, verbose_name='Phone Number')),
                ('email', models.EmailField(max_length=70, verbose_name='Email')),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
                ('date_embauche', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Embauche')),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employerapp.departement')),
            ],
            options={
                'verbose_name_plural': 'Employer',
            },
        ),
    ]
